openapi: 3.0.3
info:
  title: POC
  description: |
    Idc
  version: development

tags: []
paths: {}
components:
  schemas:
    Pageable:
      type: object
      properties:
        definetly_not_pageable:
          type: string
    PagedObject:
      type: object
      properties:
        value:
          type: string
        pageable:
          $ref: '#/components/schemas/Pageable'